### ISSUE TITLE
add tests for base functions

### ISSUE THREAD

**Issue by bc** [bc/frontiers2017#28]
- [x] signed_max_residual_val
- [x] first_true_value_idx
- [x] no_bounds
- [x] assign_new_bounds
- [x] index_of_first_stabilized_val
- [x] slow_stabilized_index
- [x] discrete_diff
- [x] sort_by_initial_index
- [x] force_trial_to_stable_index_df
- [x] delta_tension

**Comment by bc** [comment]
create commits via 
```
git commit -m '#28 Wrote functions for signed max residual'
```

**Comment by medvidov** [comment]
Added tests for signed_max_residual_val, first_true_value_idx, no_bounds, assign_new_bounds, discrete_diff, sort_by_initial_index, and delta_tension. Working on remaining tests.

**Comment by medvidov** [comment]
Added function stop_if_midpoint_out_of_range in settling_time_analysis.r.

**Comment by bc** [comment]
index_of_first_stabilized_val

cases:

for each of (integer and numeric)

a) when first is stabilized and second is stabilized
b) when first is not stabilized and second is stabilized
c) when neither is stabilized stop w Error

for 6 total cases

**Comment by bc** [comment]
For slow stabilized index, just make sure that inputs to stabilized index match slow stabilized index.
*i.e.*
``` expect_true(slow_stabilized_index(etc) == stabliized_index(etc))```

**Comment by medvidov** [comment]
Added tests for force_trial_to_stable_index_df and index_of_first_stabilized_val. Error tests for slow stabilized index do not work

**Comment by medvidov** [comment]
expect_true(slow_stabilized_index(c(1.1, 1.1), -3.1, 1.1) == stabilized_index(c(1.1, 1.1), -3.1, 1.1)) does not work, and neither does expect_error(slow_stabilized_index(c(-1, -1), -3, 1), "The time series never stabilized under the maximum allowable error threshold"). In both cases, the argument to min is returning Inf. Googling why

**Comment by medvidov** [comment]
Found that the error checking is the only thing that doesn't work for slow_stabilized_index

**Comment by bc** [comment]
checking out your branch now
