### ISSUE TITLE
settling time fig 3

### ISSUE THREAD

**Issue by briancohn** [bc/frontiers2017#7]

**Comment by bc** [comment]
<img width="495" alt="messages image 774318386" src="https://user-images.githubusercontent.com/13772726/30232966-84753178-94a7-11e7-8545-c8e83713270f.png">
<img width="747" alt="messages image 2021080547" src="https://user-images.githubusercontent.com/13772726/30232971-888e8fac-94a7-11e7-91fa-75d146b00e74.png">


The algorithm reduces the bounds of the converged area.

logic:
```
##' err is maximum allowable error
##' desired is the desired steady state value.
##' @description
##' if length of a vector V is n, and some q exists s.t. v[q:n] is stable,
##' Then any value 1 < x < Q, where x is stable, implies x:N is also stable.
##; bounds = known stability bounds
index_when_timeseries_stabilized <- function(ts, desired, err) {```

**Comment by bc** [comment]
[settling_time_analysis_performance.pdf](https://github.com/bc/frontiers2017/files/1289340/settling_time_analysis_performance.pdf)
Amortized performance improvement is ~70:6964 with A:B, where B is the divide-and-conquer approach.

replicates = 1000.


```
alg .           min        lq       mean    median        uq       max   neval
A, small vec   49.185   53.0285   61.39078   56.2815   58.5380  3386.886  1000
A, large vec   4318.198 5268.7640 6964.91586 7037.9920 7697.491 47377.97  1000
B, small vec   26.561   29.1150   40.49589   30.8245   39.8180  2976.890  1000
B, large vec   51.927   55.9115   70.18382   58.9290   67.4025  3128.235  1000
```


Produced by
```
  library(microbenchmark)
  mbm = microbenchmark(
          slow_stabilized_index(sample_vec, desired=3, err=1),
          slow_stabilized_index(sample_measured_M0_force_trial, desired=4, err=0.5),
          stabilized_index(sample_vec, desired=3, err=1),
          stabilized_index(sample_measured_M0_force_trial, desired=4, err=0.5),
          times=1000
  )
  pdf("settling_time_analysis_performance.pdf", width=10,height=10)
    boxplot(mbm, cex=0.25)
  dev.off()

```

**Comment by bc** [comment]
made sample fig for part A
![image](https://user-images.githubusercontent.com/13772726/30242773-7cc832cc-9551-11e7-8171-3580c96a4190.png)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30242898-70e56260-9554-11e7-8622-41af14109c71.png)

Number of postures recorded

**Comment by bc** [comment]
Got a working extraction function for specific forces. len(forces[,1]) matches
![image](https://user-images.githubusercontent.com/13772726/30351166-f6b24184-97ce-11e7-8f3a-8132fe83be10.png)

**Comment by bc** [comment]
Scaling test for function `get_forces_list` shows linearity in performance with `1, 10, and 100 postures`.

![image](https://user-images.githubusercontent.com/13772726/30351799-fc2add58-97d1-11e7-9651-f15651ea7448.png)


Further study shows that mclapply yields time savings:
```
0.36252s/posture with lapply
0.25935ms/posture with mclapply
```

![image](https://user-images.githubusercontent.com/13772726/30352212-a132a0d2-97d3-11e7-932a-321fe3cf2632.png)
![image](https://user-images.githubusercontent.com/13772726/30352215-a49318f6-97d3-11e7-9182-42ccc9efe967.png)

**Comment by bc** [comment]
Full experimentation on idxs[[1]]: `80.09924s`

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30440549-c4e7b9d2-992b-11e7-8522-b0ffa6147809.png)
working application of stabilized_idx on first trial of fix_x posture 1

**Comment by bc** [comment]
settling times are highly variable, even within one posture. measured_M0 settling times shown:

![image](https://user-images.githubusercontent.com/13772726/30444632-76e3d060-9938-11e7-9594-fd061795d5fa.png)

**Comment by bc** [comment]
@kian-ja check out the high variability on settling time! what does it mean?

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30452117-7812bf3a-9949-11e7-9505-83a05b790c59.png)
@kian-ja alternative view of those data

**Comment by bc** [comment]
This is for a threshold of 0.5 N

**Comment by bc** [comment]
for a different posture:
![image](https://user-images.githubusercontent.com/13772726/30452261-f208080e-9949-11e7-8202-cfbe5cd330d0.png)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30454061-e76ad0f6-994f-11e7-8253-78835a9f3c88.png)
higher variability in rise time when the change in activation is very small

when efferent signals = a high alpha drive

Speed of muscle force change is not dependent upon the amplitude of the input change.
We know that when there are high efferent alpha signals, a distribution of motor units with "fast-twitch" muscles are recruited more (these have a higher bandwidth).
That is the only way to reduce settling time.

This can help us characterize how a movement is 'fast' vs 'slow' as a function of alpha drive.

The system is stationary: it is not time varying. Not dependent on an external input (e.g. delta force).

Variability seen at 0 suggests that other muscle movement may instigate

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30559620-150c1958-9c6a-11e7-9583-cd1a747a781b.png)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30560166-e0c91b26-9c6b-11e7-8feb-1bdbc2330a61.png)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30560517-054c5dae-9c6d-11e7-9cdc-28ae8f1ba737.png)
@kian-ja signal to noise ratio plot
